--  Copyright (C) 2026 Anthony Gair
--  SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-DarkFactory-Commercial-1.0
--  Forged and machine-checked by The Dark Factory. This file is the
--  vendored copy of an IMMUTABLE wu round output. This comment block is
--  the only difference from it; nothing below this line is altered.
--  Reproduce with scripts/stamp-licence.sh in the ada-factory repo.
--  Unstamped source sha256: bd048c65ef9aeb71eba2e8e2ad8e741d87337ebf01c8170d10693aae78f37b82
--
with Ada.Command_Line;
with Ada.Directories;
with Ada.Text_IO;
with GNAT.OS_Lib;

with Build_Stamp_Pkg;

procedure stamp_build_main is

   use type GNAT.OS_Lib.String_Access;

   function Read_All (Path : String) return String is
      F    : Ada.Text_IO.File_Type;
      S    : String (1 .. 65536);
      Last : Natural := 0;
   begin
      Ada.Text_IO.Open (F, Ada.Text_IO.In_File, Path);
      while not Ada.Text_IO.End_Of_File (F) loop
         declare
            Line : constant String := Ada.Text_IO.Get_Line (F);
         begin
            for C of Line loop
               if Last < S'Last then
                  S (Last + 1) := C;
                  Last := Last + 1;
               end if;
            end loop;
            if Last < S'Last then
               S (Last + 1) := ASCII.LF;
               Last := Last + 1;
            end if;
         end;
      end loop;
      Ada.Text_IO.Close (F);
      return S (1 .. Last);
   exception
      when others =>
         return "";
   end Read_All;

   function Strip (S : String) return String is
      Last : Natural := S'Last;
   begin
      while Last >= S'First and then (S (Last) = ASCII.LF or else S (Last) = ASCII.CR) loop
         Last := Last - 1;
      end loop;
      if Last < S'First then
         return "";
      else
         return S (S'First .. Last);
      end if;
   end Strip;

   procedure Run_Git (Git : String; A1, A2, Out_File : String; Ok : out Boolean) is
      Args        : GNAT.OS_Lib.Argument_List := (1 => new String'(A1), 2 => new String'(A2));
      Success     : Boolean;
      Return_Code : Integer;
   begin
      GNAT.OS_Lib.Spawn (Git, Args, Out_File, Success, Return_Code, Err_To_Out => False);
      Ok := Success and then Return_Code = 0;
      GNAT.OS_Lib.Free (Args (1));
      GNAT.OS_Lib.Free (Args (2));
   end Run_Git;

   Commit_Ok : Boolean := False;
   Status_Ok : Boolean := False;
   Git_Path  : GNAT.OS_Lib.String_Access;

begin
   if Ada.Command_Line.Argument_Count > 0 then
      Ada.Text_IO.Put_Line (Ada.Text_IO.Standard_Error, "stamp_build_main: no arguments expected");
      Ada.Command_Line.Set_Exit_Status (3);
      return;
   end if;

   Ada.Directories.Create_Path ("obj");

   Git_Path := GNAT.OS_Lib.Locate_Exec_On_Path ("git");
   if Git_Path /= null then
      Run_Git (Git_Path.all, "rev-parse", "HEAD", "obj/stamp-commit.txt", Commit_Ok);
      Run_Git (Git_Path.all, "status", "--porcelain", "obj/stamp-status.txt", Status_Ok);
      GNAT.OS_Lib.Free (Git_Path);
   end if;

   declare
      Commit_Raw : constant String := (if Commit_Ok then Strip (Read_All ("obj/stamp-commit.txt")) else "");
      Porcelain  : constant String := (if Status_Ok then Read_All ("obj/stamp-status.txt") else "X");
      Commit     : constant String := Build_Stamp_Pkg.Recorded_Commit (Commit_Raw);
      Clean      : constant Boolean := Build_Stamp_Pkg.Is_Clean (Porcelain);
   begin
      Ada.Directories.Create_Path ("src/generated");

      declare
         F : Ada.Text_IO.File_Type;
      begin
         Ada.Text_IO.Create (F, Ada.Text_IO.Out_File, "src/generated/crucible_build.ads");
         Ada.Text_IO.Put_Line (F, "--  Copyright (C) 2026 Anthony Gair");
         Ada.Text_IO.Put_Line (F, "--  SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-DarkFactory-Commercial-1.0");
         Ada.Text_IO.Put_Line (F, "--");
         Ada.Text_IO.Put_Line (F, "--  GENERATED by stamp_build_main at build time. Do not edit: the next build overwrites it.");
         Ada.Text_IO.Put_Line (F, "--  The binary reports the tree it was BUILT FROM, measured, never a version string someone typed.");
         Ada.Text_IO.Put_Line (F, "package Crucible_Build with SPARK_Mode is");
         Ada.Text_IO.Put_Line (F, "   Commit     : constant String := """ & Commit & """;");
         Ada.Text_IO.Put_Line (F, "   Tree_Clean : constant Boolean := " & Build_Stamp_Pkg.Clean_Word (Clean) & ";");
         Ada.Text_IO.Put_Line (F, "   function Recorded return Boolean is (Commit'Length >= 7)");
         Ada.Text_IO.Put_Line (F, "     with Post => (Recorded'Result = (Commit'Length >= 7));");
         Ada.Text_IO.Put_Line (F, "end Crucible_Build;");
         Ada.Text_IO.Close (F);
      exception
         when others =>
            Ada.Text_IO.Put_Line (Ada.Text_IO.Standard_Error, "src/generated/crucible_build.ads");
            Ada.Command_Line.Set_Exit_Status (2);
            return;
      end;

      declare
         First12 : constant String := (if Commit'Length >= 12 then Commit (Commit'First .. Commit'First + 11) else "");
         Display : constant String := (if Commit'Length = 0 then "none" else First12);
         Lower   : constant String := (if Clean then "true" else "false");
      begin
         Ada.Text_IO.Put_Line ("stamped: src/generated/crucible_build.ads  commit=" & Display & " clean=" & Lower);
      end;

      Ada.Command_Line.Set_Exit_Status (0);
   end;

end stamp_build_main;
