#!/usr/bin/env bb
;; stamp-build.bb — write src/generated/crucible_build.ads from the tree this build comes from.
;;
;; WHY GENERATED, NOT HAND-WRITTEN. A binary that reports a version someone typed is reporting a
;; claim, not a fact: v0.1.1 reported 0.1.0 for exactly that reason. This file is derived from git
;; on every build, so the binary cannot say it was built from a commit it was not built from.
;;
;; A DIRTY TREE IS RECORDED AS DIRTY. The honest value is the awkward one: if the working tree has
;; uncommitted changes then the commit alone does not identify these bytes, and Provenance must
;; refuse rather than issue a receipt a stranger cannot replay.
(require '[babashka.process :refer [shell]] '[babashka.fs :as fs] '[clojure.string :as str])

(def root (str (fs/parent (fs/parent (fs/canonicalize *file*)))))

(defn git [& args]
  (try (str/trim (:out (apply shell {:dir root :out :string :err :string :continue true} "git" args)))
       (catch Exception _ "")))

(def commit (git "rev-parse" "HEAD"))
(def dirty? (not (str/blank? (git "status" "--porcelain"))))
(def out (str (fs/path root "src" "generated" "crucible_build.ads")))

(fs/create-dirs (fs/path root "src" "generated"))
(spit out
  (str "--  Copyright (C) 2026 Anthony Gair\n"
       "--  SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-DarkFactory-Commercial-1.0\n"
       "--\n"
       "--  GENERATED by scripts/stamp-build.bb at build time. Do not edit: the next build overwrites it.\n"
       "--  The binary reports the tree it was BUILT FROM, measured, never a version string someone typed.\n"
       "package Crucible_Build with SPARK_Mode is\n"
       "   Commit     : constant String := \"" commit "\";\n"
       "   Tree_Clean : constant Boolean := " (if dirty? "False" "True") ";\n"
       "   function Recorded return Boolean is (Commit'Length >= 7)\n"
       "     with Post => (Recorded'Result = (Commit'Length >= 7));\n"
       "end Crucible_Build;\n"))

(println (str "stamped: " out "  commit=" (if (str/blank? commit) "none" (subs commit 0 (min 12 (count commit))))
              " clean=" (not dirty?)))
