--  Copyright (C) 2026 Anthony Gair
--  SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-DarkFactory-Commercial-1.0
--  Forged and machine-checked by The Dark Factory. This file is the
--  vendored copy of an IMMUTABLE wu round output. This comment block is
--  the only difference from it; nothing below this line is altered.
--  Reproduce with scripts/stamp-licence.sh in the ada-factory repo.
--  Unstamped source sha256: c05f55fea72e51b753791b9fb2de7d36459d3cba1c50e15a62c9700696b19130
--
--  Tower_Keys_Pkg -- the two catalog public keys a puller trusts under ONE stream, PINNED IN THE BUILD, plus the
--  index signer's public key. Seat-written constants, no code: the way Crucible_Tower.Base_Digest and the door's
--  Pinned_Reef_Signers are pinned (BRIEF_tower_transport_2026-09-21 section 4, lean under ONE stream; the loopback
--  build brief of 2026-09-21, piece A). The trust file beside the binary (allowed_signers) is GENERATED from these
--  by bin/stamp_signers at build time -- never hand-written, never written by the agent or by the fetch edge.
--  An own-network operator substitutes their own keys here and rebuilds.
--
--  WHICH LINE IS REAL AND WHICH IS A STAND-IN, said plainly so nobody has to guess:
--    Df_Tower_Public      REAL. The df-tower signer's public half, captured from ~/.df-tower/df-tower.pub on Bill
--                         (the owner's key ceremony, decision_o3_df_tower_key_ceremony_2026_09_21).
--    Df_Admission_Public  REAL. The admitter's public half (interim-software-2026-08: the identity certify_tower
--                         signs provenance records with and admit-core.sh signs admissions with), captured at
--                         ~/ObVault/keys/admitter-interim-2026-08.pub; private half 0400 under the admitter service
--                         user on gertrude. INTERIM until the Nitrokey ceremony (ObVault/keys/README.md): re-pin then.
--    Df_Index_Public      REAL. The Reef's index signer (namespace df-index), generated by the owner on the Linode
--                         2026-09-21 (project_df_index_key_ceremony_2026_09_21); public half captured at
--                         ~/ObVault/keys/df-index.pub, fingerprint SHA256:rMVNIrVFX5WZKzRPXh5O4Eqc3aw/3K/UTrqQ4sYDF8Q
--                         confirmed against the Linode. The private half is online there by design (timestamp role).
--  bin/stamp_signers prints a warning naming every stand-in it writes, so a release with one cannot be quiet.
--  As of 2026-09-21 13:5x all three are REAL and it prints none.
package Tower_Keys_Pkg with SPARK_Mode is

   --  The principal written on every line of the trust file (the -I label ssh-keygen verifies under).
   --  CONFIRMED by the owner 2026-09-21 (closes O-3 "principal").
   Principal : constant String := "tower@thedarkfactory.co.uk";

   --  The namespaces the three seals are made under (the owner's rulings O4 and R1, 2026-09-20; D5 lean 2026-09-21).
   Tower_Namespace     : constant String := "df-tower";
   Admission_Namespace : constant String := "df-admission";
   Index_Namespace     : constant String := "df-index";

   Df_Tower_Public : constant String :=
     "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDVIPmT2iwt5H4ZCbBw3orkMeqD2GizfYsi7m2LV/AFs";
   Df_Tower_Is_Stand_In : constant Boolean := False;

   Df_Admission_Public : constant String :=
     "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJW+AtgSy5fXipztPnw94NQhHz1qlft7/lZV6SVeGc9v";
   Df_Admission_Is_Stand_In : constant Boolean := False;

   Df_Index_Public : constant String :=
     "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFL2/2ZdBY3j+0H47x4EVXCctv2wjwV6KNlOptAB7UfH";
   Df_Index_Is_Stand_In : constant Boolean := False;

   --  CONSTANTS ONLY (the owner's lean, 2026-09-21: no shape predicates here; the stamp tool writes the pins blindly,
   --  and whether the written file is one ssh-keygen accepts is the probe's row A2, not a theorem of this unit).

end Tower_Keys_Pkg;
